services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: booking-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: booking-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
      - "29092:29092"

  postgres:
    image: postgres:16
    container_name: booking-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: booking-redis
    ports:
      - "6379:6379"

  users-service:
    build:
      context: .
      dockerfile: UsersService/Presentation/Dockerfile
    container_name: booking-users-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__UsersConnection: "Host=postgres;Port=5432;Database=usersdb;Username=postgres;Password=postgres"
    ports:
      - "5001:5001"

  events-service:
    build:
      context: .
      dockerfile: EventsService/Presentation/Dockerfile
    container_name: booking-events-service
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      redis:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__EventsConnection: "Host=postgres;Port=5432;Database=eventsdb;Username=postgres;Password=postgres"
      Kafka__BootstrapServers: "kafka:9092"
      Redis__ConnectionString: "redis:6379"
    ports:
      - "5002:5002"

  bookings-service:
    build:
      context: .
      dockerfile: BookingsService/Presentation/Dockerfile
    container_name: booking-bookings-service
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__BookingsConnection: "Host=postgres;Port=5432;Database=bookingsdb;Username=postgres;Password=postgres"
      Kafka__BootstrapServers: "kafka:9092"
    ports:
      - "5003:5003"

volumes:
  postgres-data:
