@AspNetCoreApi_HostAddress = http://localhost:5030

GET {{AspNetCoreApi_HostAddress}}/api/events
Accept: application/json

###

POST {{AspNetCoreApi_HostAddress}}/api/events/91ee517e-943a-460a-a708-9371ed96a7b3/book
Accept: application/json

###
GET {{AspNetCoreApi_HostAddress}}/api/bookings/265af2cb-5859-420f-b6c3-a24f683e0d14
Accept: application/json
###

GET {{AspNetCoreApi_HostAddress}}/api/events/cd1bc33a-00f4-4b98-b2bd-d0651b3f57ff
Accept: application/json

###
POST {{AspNetCoreApi_HostAddress}}/api/events
Content-Type: application/json
Accept: application/json
{
  "title": "Открытие конференции1",
  "startAt": "2026-06-18T08:45:15.648Z",
  "endAt": "2026-06-20T08:45:15.648Z",
  "totalSeats": 5
}

###
POST {{AspNetCoreApi_HostAddress}}/api/events
Content-Type: application/json
Accept: application/json
{
  "startAt": "2025-07-15T10:00:00",
  "endAt": "2024-07-15T18:00:00"
}

###
PUT {{AspNetCoreApi_HostAddress}}/api/events/f0b8db07-8ec1-4df8-8ba5-c50d315e4c9c
Content-Type: application/json
Accept: application/json
{
  "title": "Открытие конференции3",
  "startAt": "2024-07-15T10:00:00",
  "endAt": "2026-07-15T18:00:00"
}

###
DELETE {{AspNetCoreApi_HostAddress}}/api/events/6b90521c-c198-4fdb-a524-3f5e5412a097
Content-Type: application/json
Accept: application/json